[project]
name = "github-pages-test"
version = "0.1.0"
description = "Small project to test GitHub Pages and basic packaging."
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = "==3.13.*"
license = { text = "Public Domain" }

dependencies = [
  "marimo",
  #  "markitdown[pdf]",
  "markitdown-no-magika[pdf]",
  "pypdf>=6.13.2",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
